# Description:
#   None
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   nunn me - Returns a random Nunn quote
#
# Author:
#   mittenchops, vquaiato

quotes = [
  '''I hardly know the answer to make to your letter of October 19th and the Resolution enclosed therewith.''',
  '''The problem is one of self-government; the problem which was eloquently debated on Mars Hill before the birth of Christ, which has been considered in every great epoch of the world's history, the one to which Lincoln gave his life, and the one which the enemies of the Stars and Stripes say has been demonstrated to be a failure.''',
  '''I don't believe it is a failure, moreover I believe young men facing the problem of life as students are better prepared for self-government than the average citizen of any country, of any age.''',
  '''The work of the Association is to demonstrate the feasibility and advantages of self-government and to receive as compensation for that work the benefits passed on by the success of its stewardship to those still to come.''',
  '''All is in the hands of the Association.''',
  '''The work of the Directors has been done. Their mission, to create the Association, is ended.''',
  '''The age of guardianship is passed, the die is cast.''',
  '''To the members, and the members alone, the future is entrusted.''',
  '''The only shadow of a reason for a different view might arise from a misunderstanding as to the condition of the property; but there should be no misunderstandig.''',
  '''It has been for a long time absolutely fixed by will, for months past irrevocably declared to be a trust, and just as soon as I can make a trip east, presumably before the 15th of next month, it shall be lodged in the Association.''',
  '''To the Association then, I must reply: You have no Directors, and the lives of your members must declare your purpose.''',
  '''To the "Cornell Daily Sun", it occurs to me, the Association might with dignity say;-it is a few individuals impressed with the desirability of seriously considering, during their student life, the problems they will meet in their future active career; that it owns the property that it occupies and an endowment, which by good fortune or the good judgment of its members it is constantly increasing; that it is too modest in its expectations to parade its hopes or to believe that the public can be interested in its affairs beyond the simple facts that it pays its bills, minds its own business, and leaves its members free to form and maintain such relations with outside institutions and individuals as each in his individual capacity may elect, only requiring honorable conduct of all.''',
  '''It is impossible to state the purpose of a single life, nor can the purpose of the Association be stated without narrowing it to a falsehood. ''',
  '''You might say, as in the case of the Smithsonian, "For the increase and diffusion of knowledge", but any such declaration would be a presumptuous embarrassment. ''',
  '''The wise management of your own affairs is no small matter and by accomplishing it the members will be prepared for the conduct of important affairs when they pass from their college life. ''',
  '''The conditions of membership should not be given to the public. ''',
  '''Other organizations do not publish their private affairs and if idle curiosity is allowed to beat itself upon the wires of its cage, no harm will result therefrom. ''',
  '''It should be a source of pride, rather than otherwise, that "The Faculty knows nothing about it".''',
  '''As to the statement that the members know nothing as to the purpose, I can only say that the confession is a disgrace to each one making it; for each one should know that his purpose is to execute well his stewardship, so as to leave the Association a little stronger if possible financially, and in all events stronger in honorable tradition than he found it; and that he goes out into the world better prepared to protect and nourish the interests committed to his charge, and to point, by his life at least, the better way within the community in which he lives.''',
  '''In my humble opinion the talk about an explanation is the sheerest rot; but whatever it may be, the Institution itself and not outsiders should say what is said. ''',
  '''After all, should it be so remarkable that mature students should be devoting their attention to the conduct of important affairs instead of going wild over football and shinny? ''',
  '''This, too, is a question for the Association.''',
  '''I greatly appreciate the honor you do me by requesting in your letter of May 18th my views as to what should be taken up by the coming convention.''',
  '''Members of Telluride Association, as trustees of its property, are irrevocably pledged to use Association resources for the advancement of individual freedom and wise self-regulation as means to the main end of "promoting the highest well being."''',
  '''The Preamble of the Constitution has been called vague. It is not vague. ''',
  '''It states, in philosophic language, just the above. "Well being," which is a term well understood by all thinkers, is stated as the purpose, and freedom and self-control as the means by which the purpose is to be attained. ''',
  '''To be sure, the Preamble adds "broadening the field of knowledge and increasing the adoption, as the rule of conduct, of those truths from which flows individual freedom." But knowledge is necessary to wise selfcontrol, and the adoption of rules of conduct consistent with freedom is essential to the obtaining and maintaining of freedom.''',
  '''To reply definitely, then, to your inquiry: The coming Convention should investigate the Association's doings of the past year and ascertain the efficiency obtained by the trustees from the funds of the Association in promoting its declared purpose.''',
  '''In considering efficiency, reference will undoubtedly be made to the past as well as to future opportunity. In the early days of the Association, a quarter of a century ago, it led in progressive work not confined to its members, but of value to the world. ''',
  '''It was prominent in the application of air to remote transmission of power; it was conspicuous in the use of water under high pressure; it introduced many new mechanical appliances and methods in mining and milling; it became conspicuous in pioneer alternating electric current work. ''',
  '''But such matters were only incidental results of the progressive spirit which was widely felt in more important ways.''',
  '''Within the limits of its operations, it protected labor against disease and undue danger; it advanced education; it breathed a democratic spirit into all classes in the communities in which it operated, so that harmony pre*Early associate of L.L. Nunn and member of T.A. availed where strife had previously existed between employer and employee.''',
  '''The convention adopting the Constitution did not declare that the purpose SHALL be, but that "the purpose IS to promote well being." ''',
  '''The Convention had a quarter of a century of history and tradition to guide it, and the Constitution was more a declaration in writing of what was and what had been for a long time the unwritten law of the Association than new rules for the future.''',
  '''There are those among the old veterans who had made the Association, or the Institute as it was then called, conspicuous for honorable and noble achievement, who feel, and perhaps correctly, that the present trustees of its honor and its funds are not fulfilling the obligations of their trust. ''',
  '''Attention is called to the fact that little is being done to promote general well being outside of the Association, that in too many instances the members themselves are not examples of freedom and manly self-control, and that expenditures on their behalf do not produce efficient results.''',
  '''To be more specific: Failure to control one's finances results in disastrous bondage-undermines character and destroys the power to discern equities. ''',
  '''Some of the most startling instances have occurred within the past year of members actually thinking themselves ill-treated when they were required to pay their honest debts. ''',
  '''The income of the individual has little to do with the matter. ''',
  '''It is plainly a question of self-government. ''',
  '''This subject should be investigated and action should be taken by the Convention.''',
  '''Perhaps the Association should require members and applicants to keep accurate, systematic accounts and render monthly balance sheets to a financial committee.''',
  '''Such balance sheets should not show expenditures in detail or reveal private affairs, but simply show totals of perhaps a dozen accounts, such as traveling, clothing, amusement, books, etc. ''',
  '''Such a practice would be of the greatest help to new members and would relieve them from much embarrassment and many mistakes.''',
  '''The Association should investisate the subject of the use of intoxicants and the effect on the efficiency of the Association and the individual. ''',
  '''Why should an institution claiming to be in the advance ranks ignore a matter of such vast importance which has received especial attention from the principal Governments of the world, including England, Germany, and our own?''',
  '''Permitting intoxication by the members violates the fundamental trust of the Association, and the Convention should consider whether or not the use of intoxicants should be permitted.''',
  '''The use of tobacco and its effects on the Association and the individual should be investigated, and the Association should be governed by the results of such investigation. ''',
  '''If tobacco destroys the moral sense, reduces the scholastic standing, destroys ability to reason clearly and correctly, injures the judgment of the members in their life work, and endangers the Association through the general conduct of its affairs, its use is surely contrary to the declared trust.''',
  '''General deportment should be considered and an effort made to secure more uniform results. ''',
  '''There must be some reason for the deplorable moral vision shown in a number of instances, such as the justification of improper experiences by the asserted desirability of knowing how one feels after having indulged. ''',
  '''The same argument might be urged in favor of committing forgery, rape, or any other act, but I will not refer to instances.''',
  '''They will be brought up by the scores if the Convention goes into the subject of efficiency in order to determine who should and who should not receive appropriations. In many instances it would be found that a dollar has not done the work which fifty cents should have done; that preferments have too often been the result of personal sentiment rather than principle; that an attitude of lawless unitism better adapted to the savage who recognizes no obligation to the community in which he lives and relies on his brute force or cunning than to members of an Association under the obligation assumed by the execution of the declaration of trust, has too often been indulged in.''',
  '''The impulsive selection of officers without due consideration as to their fitness by reason of their experience and general qualifications should be checked by by-laws or tradition.''',
  '''The degree of self-government which should be extended by the Association to its different Branches should be considered. ''',
  '''The failure of various Branches to enforce business integrity and the fulfillment of personal promises on the part of its members should be taken up in connection with the problem of Branch Government.''',
  '''The above suggestions refer to members. ''',
  '''The whole problem of perpetuating the Association by carefully selecting new members from the large numbers of applicants should be provided for by the appointment of a committee to act in conjunction with the Chancellor and Dean.''',
  '''I beg you not to misunderstand what I have written or the spirit which has prompted it.''',
  '''I have no desire to exercise any influence over Association affairs beyond the power of my single vote and my appeal to the judgment of my fellow members. ''',
  '''I am not losing faith in democratic principles as adopted by the Association, but I recognize a certain wobbling and the necessity for more ballast to protect the ship in the storm. ''',
  '''The failure of popular government in the past has been occasioned by the lack of the exercise of high moral principles by the people, and in our own little affairs the tendency to usurpation of power has grown out of popular errors and well intended effort to correct them.''',
  '''What are the purpose and plan of the ocean? Of this nation? Of an acorn? ''',
  '''To assume that purpose and plan exist in connection with these, we must assume a master of them. ''',
  '''The purpose and plan are not in or of the ocean, the nation or the acorn, each developing, or, as Darwin might say, evolving, as compelled by external impulses.''',
  '''Telluride Association was not planned. ''',
  '''It has merely grown, or developed. ''',
  '''When, after more than twenty years of growth without a rule or a declaration as to purpose, it adopted a Constitution, that Constitution was merely a statement of rules of conduct which had grown up and existed for a long time. ''',
  '''It was not a declaration of what should be, but of what had been, at least as to methods; and the purpose which had been and which was as a result of growth, not somebody's idea of what should be in the future but merely the motive of the past put into words, you will find in the first seven lines of the Preamble.''',
  '''The Association is at the present time the result of efforts to know and do things. ''',
  '''It is not the result of anybody's kindly effort "to help poor, worthy young men to go to school." ''',
  '''Its primary work has never been to help anybody, but rather to bring together persons who did not need help. ''',
  '''Birds of a feather flock together, and the Association will accomplish more when it brings together, by natural laws of attraction, those too strong to need help, but who are standing for advancement -for things worth while....''',
  '''No one planned the Association and the Constitution, and records of the proceedings of the Conventions are the best description of what it is.''',
  '''I was much interested in a description of the Association given by Judge Vann, of the Supreme Court of the State of New York, in his decision respecting the exemption of its property from taxation by the State of New York. ''',
  '''I think he showed by the decision a clearer understanding of the workings of the Association than is held by most of its members.''',
  '''To answer your question: The Association was not conceived, or born, but just grew to what you see it now. ''',
  '''The process of its development no one knows. ''',
  '''For its purpose, see the Preamble of its Constitution. ''',
  '''For its methods, see the Constitution, By-laws and records of the proceedings of its Conventions.''',
  '''One of the most effective methods used by diplomats when unable to secure the action they desire is to confuse the situation, by injecting into the conferences a vast multitude of points to be considered, instead of simplifying the discussion by directing the attention on a few really vital points.''',
  '''Success or failure of Telluride Association depends primarily on one point.''',
  '''Success or failure of every self-governing body depends on that same point.''',
  '''It lies at the very foundation of business partnership, of equality, of justice, of fair dealings. ''',
  '''It cannot be applied to vast numbers. ''',
  '''Consequently the members of large institutions, like nations, cannot be really self-governing, but only approximately so through their representatives.''',
  '''Small organizations such as Telluride Association can act directly, each member having an equal voice. ''',
  '''Nightingale's recommendation to establish secret voting was the opposite of the necessary condition above referred to, and, if adopted, would have at least destroyed the Association as originally intended.''',
  '''You have already recognized what this point is. It is more easily recognized than described. It is the genuine of which tattling is the counterfeit. It is action as spontaneous and natural as breathing or the beating of a normal heart. ''',
  '''It is not only consistent with, but promotes comradeship, devotion, friendship, good will, and loyalty towards all. It recognizes man's limitations and infinite possibilities. ''',
  '''It cooperates with the evolution of character and perfection through effort and correction, repentance and forgiveness, which are essentials to moral growth. ''',
  '''Instead of demanding that an associate as he runs should not trip and fall, it demands that when he trips and falls he should quickly arise and continue the race; that ofttimes he should not be denounced for falling but for his conduct after the fall.''',
  '''The facts connected with his falling, rising, and continuing the race, and his spirit in connection with the same should be seen and acted upon by those interested, as fully as the facts relating to his physical health, scholastic standing, or general prosperity.''',
  '''Every government whether it be large or small, directing the affairs of a great nation or merely those of a family, necessarily involve three distinct functions: legislative, judicial, and executive. ''',
  '''In an absolute self-governing democracy where each acts directly for himself instead of through representatives, each is necessarily an official legislator, executive, and judge, not so much of his own conduct as of the conduct of each and every member. Self-accusation, self-judging, and self-punishing are all right for the individual, but the attempt to impose such upon him from the outside by his organization or association is repugnant to the spirit of our laws, to common sense, and justice.''',
  '''We look with suspicion on a man's opinion of himself.''',
  '''Usually his ideas of what he should be required to do, of how he has conducted himself, and of the justice he receives, are very different from his ideas respecting his neighbors or fellow citizens when acting as he does. ''',
  '''No man should be expected to condemn himself but he should be expected to expect his associates to condemn him when necessary and to demand that he shall maintain the honor and dignity of the association he is connected with.''',
  '''Tattling is the telling on the outside that which should be brought out spontaneously on the inside. ''',
  '''It might be tattling for a boy to report the misconduct of his brother to either his father or his mother. ''',
  '''In many instances parents put themselves on the outside with their children when they should be on the inside.'''
  '''This point which I am trying to make clear is obscured by conflicting emotions and motives, but it should be seen that it is not tattling for one member of a copartnership constituting a business firm, to talk freely in a meeting of the partners respecting personal character and conduct which affects the success or failure of the business.''',
  '''It would be tattling for that member to tell his wife, his mother, his sister, his father, his brother, or his nearest friend, who was not a member of the firm,matters of a personal nature concerning the affairs of the copartnership or the individual partners.''',
  '''Pertaining to a self-governing institution: to the inside, all should be revealed; from the outside, all should be concealed.''',
  '''It is a vastly greater crime against Telluride Association for a member to know that another member has violated a comparatively unimportant but positive requirement of the Association and conceal that knowledge from the organization, than for him himself to go on a prolonged debauch and break every declared principle of the Association and then do his uttermost to conceal the fact. ''',
  '''It is better for the Association that a member shield himself at the expense of another member than to shield the other member at his own expense. ''',
  '''Note, I say, better for the Association, not for him. ''',
  '''The member who conceals the misconduct of others commits a greater offense against the Association than those guilty of the specific offenses.''',
  '''There is not a human being on this whole earth whose moral evolution has proceeded so far, and who has sufficient strength to withstand the tremendous pressure of a secret life, and yet it is natural for every human being to conceal his faults. ''',
  '''No success will be had by leaving each to police himself. ''',
  '''Justice to the organization requires that each police the whole, from the inside-not from the outside. ''',
  '''Honesty as trustees requires that the trusteed property be protected against destruction. ''',
  '''This includes the declared purpose, character, and traditions as well as money. ''',
  '''For years you have heard-me-talk on this subject but my talk has been without results, because it cut traditions, based on prejudice and ignorance, cross-grain.''',
  '''I had hoped the older members would study the character of self-government. ''',
  '''Where government is from the outside, where a special class is employed to police and harass, reporting in most cases is infamous. ''',
  '''But where there is no police, no government except the governed, the organization cannot exist without the recognition and adoption of the principle that equal rights impose equal responsibilities to legislate, police, and punish. ''',
  '''I have repeatedly said to the older members, "By concealing you are placing burdens on the weak which even the strong cannot bear. By revealing you will assist all to do what all want to do."''',
  '''Those who fall the most are not those who want to fall, nor do they fall because they are weak, but they often stumble because they carry heavy burdens in the dark which they could carry without faltering if they walked in the light of the truth, in the bright light of day. ''',
  '''It is too much to expect them, as indeed it is too much to expect of anyone, to turn the searchlight on himself for the public gaze, but they are strengthened in their walking so long as the searchlight is turned upon them, and they grow stronger and stronger and walk steadier, which, after all, is the great mission of life.''',
  '''This applies to all. There is no much difference between us.''',
  '''You know I have never been much in sympathy with the idea of ejecting members because of their faults. ''',
  '''In many instances those ejected would be no worse material than those retained. ''',
  '''I would keep all in the open air under the searchlight, so far as their conduct relates to the Association.''',
  '''Then, should there be anyone antagonistic in spirit to the purpose of the Association, he should be eliminated. ''',
  '''This should apply equally to the selfish, self-satisfied, so-called correct liver who neglected his duty to the organization and did nothing to raise or even maintain its standards, as to the one of low scholarship or evil tendencies.''',
  '''Is it not possible to have this one point studied and comprehended by a score of our more mature members and then so diffused as to be made a tradition which in turn should be studied, comprehended and adopted by every applicant before admission to membership is not possible to have it understood so that instead of appearing in an offensive manner, it appears as it really is, a glorious pillar of strength to those who wish to accomplish for themselves, for their Association, for the community in which they live and work, for their country, for their God, something worthwhile.''',
  '''It is hard for me to restrain a feeling of contempt and condemnation for those who, having had remarkable educational opportunities, yet remain bound down by prejudices, bigotry, and religious fanaticism. ''',
  '''A general desire and disposition in the organization "to know the truth" is the only power capable of regenerating such. That intellects keen on many subjects can continue blind to the essential requirements of self-government of an institution reflects discredit on the organization. ''',
  '''Such darkness would be impossible in the midst of great light. ''',
  '''Comprehension by a score of members of the relation between the real and the counterfeit, between governing and tattling, would soon percolate through the entire membership and establish traditions which would overcome the present evils, and give new life to the organization. ''',
  '''If the Association is to receive boys for education, let it start that education with a knowledge of the character and necessary requirements 'of self-government. ''',
  '''It should be made plain to each that he will be called upon to legislate, to police, to judge, and to execute, and that loyalty to the spirit rather than the letter will be demanded: that he will be required to "judge justly, love mercy and walk humbly": that neither he nor his associates even approximate perfection in their conduct but that the spirit of progress by error and correction, by repentance and forgiveness should be the watchword, and should impregnate all.''',
  '''I feel like blaming you for the condition revealed by your statement....''',
  '''Gentlemen: My observation leads me to suspect that the widest chasm between the Association as it exists in theory and as it exists in practice may be explained by a disregard of that portion of our trust declared in the latter half of the preamble.''',
  '''After declaring our purpose to be the promotion of the highest well being, the preamble prescribes two ways in which we are to pursue that purpose. ''',
  '''First, we are to broaden the field of knowledge. ''',
  '''This course is fairly comprehensible to us. ''',
  '''But when we are asked to adopt as the rule of our conduct those truths from which flows individual freedom as the result of self-government in harmony with the Creator, it seems that our perception grows dim. ''',
  '''The idea that individual freedom and self-government in obedience to law are one and the same thing appears somewhat as a paradox. ''',
  '''Yet this is the purport of the preamble. It states that those laws which are in harmony with the Creator are truths and that freedom will be, attained by their adoption of our own individual volition.''',
  '''It prescribes selfgovernment by the voluntary adoption of rules of conduct ordained by a superior power. ''',
  '''Self-government is of course used as synonymous with self-restraint, and it is the superficial verbal contradiction between restraint and freedom which has caused this part of the preamble to pass unnoticed as something insoluble.''',
  '''To not a few, the idea of securing individual freedom by living above a law which would otherwise be enforced against us is a phantom freedom. However, I have found no one who, upon reflection, could discover any other kind of freedom. ''',
  '''In endeavoring to reconcile restraint with freedom, I do so because I have seen but little self-restraint in the Association, in that its laws have been respected or disrespected too largely according to temperament. ''',
  '''All our life is lived under law. ''',
  '''Law is universal, whether it be the law of nature, of government, or of subordinate institutions. ''',
  '''For instance, consider the domain of natural law. It is a law of nature that water shall run down hill and not up hill; that a tree shall spread its roots beneath the soil and not above; that night shall succeed day; that the planets shall revolve in orbits; that a cause shall have an effect.''',
  '''Nowhere in nature do we have anything operating free from law. The more we investigate anything the more laws we find in it. In fact we know it only through the laws of its being.''',
  '''The exposition of the nature of anything is nothing more than the exposition of its laws. ''',
  '''So, if a man wishes to concern himself with nature he does so by first obeying its laws. If he wishes to utilize the natural forces of light and electricity he proceeds first to learn the laws by which they operate and then conforms to them. He does not, in the name of freedom, undertake to control the forces of nature by an autocratic command. ''',
  '''It would hardly be profitable for our legislature to enact statutes purporting to reverse the law of gravity or the movement of the tide. ''',
  '''We realize that natural law is irresistible and inflexible, and we proceed to conform to its mandates, pleasantly or unpleasantly, but nevertheless conform. Our so called adaptation of nature to man's needs is thus nothing but an adoption of its law in our undertakings. ''',
  '''It is as true to say that the fruit of modern science is as much an adaptation of man to nature as of nature, to man.''',
  '''But nature is not the sole source of our law. Man makes it. We have the constitutions of the United States, of New York State, and of private, institutions.''',
  '''We have federal statutes, state statutes, municipal ordinances.''',
  '''And beyond these written laws we have an infinite number of unwritten laws governing our daily social conduct. ''',
  '''In whatever sphere we move, our every act brings some law into operation.''',
  '''Whether it be the payment of a sum of money for an article of merchandise in conformity to the law of compensation, or a journey from one place to another along a designated route called a public highway in conformity to the mandate not to trespass, or an obeisance in the drawing room in conformity to the law of courtesy whatever the act may be, it brings some law, written or unwritten, into effect. ''',
  '''I do not mean to say that this operation of law is all conscious.  To the contrary, most of it is unconscious, and that is the significant thing for us.''',
  '''When the law and one's natural act are in accord, there is no question of restraint, no problem of individual freedom. Nor do I mean to say that there is no such thing as disregard of the law, but the law nevertheless comes into sway in the form of a penalty. ''',
  '''For instance, the laws of health may be disregarded, as may also the laws of property, in which case, however, we have neither health nor prosperity. But the question of penalties is not the one I am now interested in. ''',
  '''For the present, it is sufficient to sharpen our realization of the universality of law.''',
  '''Notwithstanding this universality of law, the words of freedom and liberty remain shibboleths of all times. ''',
  '''We still regard the United States as a land of liberty, notwithstanding the many massive volumes necessary to contain its many statutes.''',
  '''The problem of our preamble will be solved if we can reconcile this sway of law with the freedom of the individual living under the law.''',
  '''I submit to you that there is and can be of necessity only one form of freedom, and that is a living above the law, or as the preamble states it, an adoption as the rule of conduct of those truths from which flows individual freedom as a result of self-government in harmony with the Creator. ''',
  '''To live above the law, to adopt it as the rule of conduct, means voluntary conformity as distinguished from involuntary conformity. ''',
  '''And it is this voluntary feature of conformity which opens the door to individual freedom.''',
  '''I said above that much of our conformity to law was unconscious.  It is also temperamental. Governmental law, being begotten of man, naturally reflects public opinion, and most people are by their disposition in accord with the law.''',
  '''Our natural conduct is in accord with the law in most of its domain.  Hence, its mandatory character is not interpreted as an abridgment of our individual freedom. ''',
  '''For instance, we have obeyed the law forbidding murder, and I dare say that we should have refrained from such a deed, even though no prohibition existed. ''',
  '''Much of our lawful conduct is of this predispositional character, and that is why the idea of individual liberty remains. ''',
  '''Where a law is obeyed voluntarily, it is not considered restraint.''',
  '''But of course our temperaments do not bring us into accord with all of the law. ''',
  '''Being an expression of the opinion of the majority of voters, it follows that the law is unrepresentative of this minority. ''',
  '''Most of us have been in the minority at some time or other on some law and it follows that for most of us there is a portion of the law that is disagreeable. ''',
  '''It is just here that temperament ceases to provide for freedom and that self-government and self-restraint must step in if the freedom of the individual is to be complete.  He must by his own initiative and voluntary adoption of the law of his organization achieve his individual freedom.  His organization may be the nation, the state, or Telluride Association. ''',
  '''Our subscription of the Constitution and our acceptance of membership pledged us to this selfgovernment, individually and collectively.''',
  '''Do not understand me to advocate the adoption of any law regardless of its source and the manner of its promulgation. ''',
  '''To the contrary, I believe that all governments receive their just powers from the consent of the governed. ''',
  '''But it is unnecessary to consider this phase of the problem because no member of the organization alleges that his membership came into existence in any manner other than by his consent.''',
  '''The authority of the Constitution and of the laws passed in accord therewith are the laws of a government whose powers are derived from the governed.''',
  '''Nor is it to be inferred that I deny the right of reformation to the law of Telluride Association, whether the law in question be the acts of the conventions or the Constitution itself. ''',
  '''But I simply direct your attention to the fact that this law provides its own method of reformation. ''',
  '''There is no justification for the suspension of this legitimate means of reformation, in favor of anarchy or arbitrary individuality repudiating its trusteeship.''',
  '''In conclusion, permit me to epitomize what I have said. Law is universal. ''',
  '''Involuntary compliance means a loss of freedom whereas voluntary compliance means its attainment. ''',
  '''Freedom and living above the law are one and the same thing. An important feature of membership in our organization is the attainment of this freedom. ''',
  '''Our constitutional obligation prescribes the voluntary adoption of natural law, of the laws of a government deriving its power from the governed, and of such other rules of conduct as promote the highest well being and are thereby in harmony with the Creator.''',
  '''Telluride Association is not a corporation but a self-perpetuating organization. ''',
  '''It has been in active operation about thirty years, but until nine years ago it had no written constitution, being controlled by the necessities of the hour, thereby building up traditions and precedents which gradually accumulated during the twenty years prior to its adopting a written constitution.''',
  '''Ten years ago thirty members were appointed to formulate a constitution from such traditions and precedents. They spent practically two months in preparing a draft, copy of which was sent to each member. ''',
  '''A year later a constitutional convention was called which lasted about three weeks and was attended by nearly all of its members. ''',
  '''The aim of the convention was not to originate new rules of action but to declare in clear and concise language the rules which had governed in the past. The sessions were from one in the afternoon till late in the evening, sometimes extending until midnight. ''',
  '''The mornings were taken up with committee work.''',
  '''Full report of discussions on the floor were printed between midnight and the afternoon session following so that each member found on his desk a printed report of all that had been said the day before.''',
  '''The result was a very short and unique document. A copy will be mailed you from Provo so that you can judge for yourself.''',
  '''The Cornell department is only a branch.''',
  '''Considering this fact, the boys were perhaps a little extreme in putting up so fine a building there as they did.''',
  '''It is undoubtedly the best built of any on the campus and wonderfully adapted to the higher Association life.''',
  '''Although built with the greatest economy during the low-cost period, they spent approximately $140,000 in its construction and furnishings.'''
]

module.exports = (robot) ->
  robot.hear /.*(nunn).*/i, (msg) ->
    msg.send msg.random quotes

